---
 - name: Ensure IIS webserver is installed
   win_feature:
     name: Web-Server
     state: present

 - name: Deploy default iisstart.html file
   template:
     src: iisstart.j2
     dest: c:\inetpub\wwwroot\iisstart.htm

